spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DevDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: woqls129

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#      location: \home\ec2-user\apps\IC-Capstone-User-Traders\UserTraders-frontend\src\assets\images\

  devtools:
    livereload:
      enabled: true
    restart:
      enabled=false:

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080





